//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyName()
        {
            this.CountryCompNames = new HashSet<CountryCompName>();
        }
    
        public int CompanyID { get; set; }
        public string ExchangeCode { get; set; }
        public string CompanyName1 { get; set; }
        public string ShortCode { get; set; }
        public string CorpInfor { get; set; }
        public string CountryID { get; set; }
        public Nullable<int> BusinessSectorID { get; set; }
        public Nullable<int> CompanyTypeID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual BusinessSector BusinessSector { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual Country Country { get; set; }
        public virtual Exchange Exchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryCompName> CountryCompNames { get; set; }
    }
}
