//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CompanyCaptureDBEntities2 : DbContext
    {
        public CompanyCaptureDBEntities2()
            : base("name=CompanyCaptureDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessSector_tbl> BusinessSector_tbl { get; set; }
        public virtual DbSet<CompanyName_tbl> CompanyName_tbl { get; set; }
        public virtual DbSet<CompanyType_tbl> CompanyType_tbl { get; set; }
        public virtual DbSet<Country_tbl> Country_tbl { get; set; }
        public virtual DbSet<CountryCompanyName_tbl> CountryCompanyName_tbl { get; set; }
        public virtual DbSet<Exchange_tbl> Exchange_tbl { get; set; }
        public virtual DbSet<User_tbl> User_tbl { get; set; }
    
        public virtual ObjectResult<SearchCompany_Result> SearchCompany(string companyName)
        {
            var companyNameParameter = companyName != null ?
                new ObjectParameter("companyName", companyName) :
                new ObjectParameter("companyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchCompany_Result>("SearchCompany", companyNameParameter);
        }
    }
}
