//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyName_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyName_tbl()
        {
            this.CountryCompanyName_tbl = new HashSet<CountryCompanyName_tbl>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string shortCode { get; set; }
        public string corpInfo { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> countryID { get; set; }
        public string exchangeCodeID { get; set; }
        public Nullable<int> companyTypeID { get; set; }
        public Nullable<int> businessSectorID { get; set; }
    
        public virtual BusinessSector_tbl BusinessSector_tbl { get; set; }
        public virtual CompanyType_tbl CompanyType_tbl { get; set; }
        public virtual Exchange_tbl Exchange_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryCompanyName_tbl> CountryCompanyName_tbl { get; set; }
    }
}
