//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCompName
    {
        public string CountryID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual CompanyName CompanyName1 { get; set; }
        public virtual Country Country { get; set; }
    }
}
