//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exchange_tbl()
        {
            this.CompanyName_tbl = new HashSet<CompanyName_tbl>();
        }
    
        public string exchangeCodeID { get; set; }
        public string exchangeName { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> countryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyName_tbl> CompanyName_tbl { get; set; }
        public virtual Country_tbl Country_tbl { get; set; }
    }
}
